
const apiPrefix = "/api"
export const routes = Object.freeze({
    auth: apiPrefix + "/auth",
    readUser: apiPrefix + "/users/:user",
    updateUser: apiPrefix + "/users",
    createGroup: apiPrefix + "/groups",
    readGroup: apiPrefix + "/groups/:organization",
    deleteGroup: apiPrefix + "/groups/:organization",
    readGroups: apiPrefix + "/groups",
    updateGroupLogo: apiPrefix + "/groups/:organization",
    generateTag: apiPrefix + "/tags/:organization/generate",
    verifyTag: apiPrefix + "/tags/:organization/verify/:tag",
    verifyTagWeb: apiPrefix + "/tags/:organization/verifyweb/:tag",
    premium: apiPrefix + "/groups/:organization/premium",
    addMember: apiPrefix + "/groups/:organization/members",
    updateMember: apiPrefix + "/groups/:organization/members/:member",
    readMembers: apiPrefix + "/groups/:organization/members",
    deleteMember: apiPrefix + "/groups/:organization/members/:member",
    deals: apiPrefix + "/premium/deals",
    addGroupInstagram: apiPrefix + "/groups/:organization/instagram",
    readRedemptions: apiPrefix + "/groups/:organization/redemptions",
    checkClient: apiPrefix + "/client/verify",
    open: "/",
})